// src/data.js

export const courses = [
  // --- Technology & Coding (1-15) ---
  { id: 1, name: 'React Fundamentals', category: 'Frontend', duration: '8 weeks', instructor: 'Alice Johnson' },
  { id: 2, name: 'Advanced JavaScript Patterns', category: 'Frontend', duration: '6 weeks', instructor: 'Bob Smith' },
  { id: 3, name: 'Python for Data Science', category: 'Backend', duration: '12 weeks', instructor: 'Charlie Chen' },
  { id: 4, name: 'Node.js & Express API Development', category: 'Backend', duration: '10 weeks', instructor: 'Dave Miller' },
  { id: 5, name: 'UI/UX Design for Mobile Apps', category: 'Design', duration: '4 weeks', instructor: 'Eve Davis' },
  { id: 6, name: 'Introduction to Cloud Computing (AWS)', category: 'Cloud', duration: '16 weeks', instructor: 'Frank White' },
  { id: 7, name: 'Cybersecurity: Ethical Hacking', category: 'Security', duration: '8 weeks', instructor: 'Grace Hall' },
  { id: 8, name: 'Machine Learning with TensorFlow', category: 'AI/ML', duration: '14 weeks', instructor: 'Henry Green' },
  { id: 9, name: 'Database Management with SQL', category: 'Data', duration: '5 weeks', instructor: 'Ivy King' },
  { id: 10, name: 'Unity 3D Game Development', category: 'Gaming', duration: '18 weeks', instructor: 'Jack Lewis' },
  { id: 11, name: 'DevOps & CI/CD Pipelines (Jenkins)', category: 'DevOps', duration: '9 weeks', instructor: 'Kelly Adams' },
  { id: 12, name: 'Web Accessibility Standards (WCAG)', category: 'Frontend', duration: '3 weeks', instructor: 'Leo Brown' },
  { id: 13, name: 'Blockchain and Cryptocurrency Basics', category: 'Finance', duration: '7 weeks', instructor: 'Mia Clark' },
  { id: 14, name: 'IoT Programming with Raspberry Pi', category: 'Hardware', duration: '11 weeks', instructor: 'Noah Scott' },
  { id: 15, name: 'Advanced TypeScript', category: 'Frontend', duration: '4 weeks', instructor: 'Olivia Harris' },
  { id: 16, name: 'Quantum Physics Explained', category: 'Science', duration: '10 weeks', instructor: 'Peter Wilson' },
  { id: 17, name: 'Introduction to Nuclear Fission', category: 'Nuclear', duration: '15 weeks', instructor: 'Quinn Taylor' },
  { id: 18, name: 'Astrobiology and the Search for Life', category: 'Science', duration: '8 weeks', instructor: 'Rachel Moore' },
  { id: 19, name: 'Mechanical Engineering Drawing (CAD)', category: 'Engineering', duration: '6 weeks', instructor: 'Sam Evans' },
  { id: 20, name: 'Applied Thermodynamics', category: 'Engineering', duration: '12 weeks', instructor: 'Tina Wright' },
  { id: 38, name: 'Modern Calligraphy', category: 'Arts', duration: '6 weeks', instructor: 'Marcus Vance' },
  { id: 39, name: 'Financial Planning for Beginners', category: 'Finance', duration: '8 weeks', instructor: 'Natalie West' },
  { id: 40, name: 'Public Speaking and Debating', category: 'Skills', duration: '9 weeks', instructor: 'Owen Xavier' },
  { id: 41, name: 'Yoga for Stress Reduction', category: 'Health', duration: '6 weeks', instructor: 'Pamela Hill' },
  { id: 42, name: 'Advanced Rock Climbing Techniques', category: 'Sports', duration: '10 weeks', instructor: 'Quentin Jones' },
  { id: 43, name: 'Mediterranean Cooking Class', category: 'Cooking', duration: '4 weeks', instructor: 'Riley Bell' },
  { id: 44, name: 'Tennis Strategy and Drills', category: 'Sports', duration: '8 weeks', instructor: 'Sam Evans' },
  { id: 45, name: 'Wilderness Survival Skills', category: 'Outdoors', duration: '12 weeks', instructor: 'Taylor Ward' },
  { id: 46, name: 'First Aid and CPR Certification', category: 'Health', duration: '3 weeks', instructor: 'Uma Green' },
  { id: 47, name: 'The Art of Negotiation', category: 'Skills', duration: '7 weeks', instructor: 'Vance White' },
  { id: 48, name: 'Personal Fitness Training', category: 'Health', duration: '16 weeks', instructor: 'Willow Adams' },
  { id: 49, name: 'Advanced Scuba Diving', category: 'Sports', duration: '5 weeks', instructor: 'Xavier Hall' },
  { id: 50, name: 'Beekeeping for Beginners', category: 'Hobby', duration: '9 weeks', instructor: 'Yasmine King' },
];